version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    # environment:
    #   - DB_HOST=192.168.8.213
    #   - DB_PORT=5433
    #   - DB_USERNAME=postgres
    #   - DB_NAME=Picaso
    #   - DB_PASSWORD=Picaso
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    env_file:
      - .env
    ports:
      - "${db_port}"
    container_name: picaso
    volumes:
      - ./postgres:/var/lib/postgresql/data